sudo: required
language: javascript

services:
  - docker

# From https://stackoverflow.com/a/24600210/2781800
# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

script:
  - make withdocker
  - docker build -t horgix/hugo:latest .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push horgix/blog:latest;
  - 'curl -L -X PUT "https://marathon.horgix.eu/v2/apps/blog" -H "Content-type: application/json" -d @marathon_app.json -u "$MARATHON_USERNAME":"$MARATHON_PASSWORD";'
  #- 'curl -L -X POST "https://marathon.horgix.eu/v2/apps/blog/restart" -H "Content-type: application/json" -u "$MARATHON_USER":"$MARATHON_PASSWORD";'
