title = "Horgix' blog"
base_url = "https://blog.horgix.fr"
author = "Horgix"

description = "TODO"

theme = "anemone"

compile_sass = false
build_search_index = false
minify_html = true

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

default_language = "en"
taxonomies = [
    {name = "tags", feed = true},
    {name = "categories", feed = true},
]

[markdown]
render_emoji = false
external_links_target_blank = true
smart_punctuation = true
#bottom_footnotes = false
highlight_code = true
highlight_theme = "gruvbox-dark" # TODO CHANGE

#[languages.fr]
#weight = 2
#languageName = "Français"
#languageCode = "fr"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "error"
external_level = "warn"


[extra]
author = "Horgix"
display_author = true

favicon = "favicon.ico"
image = ""

default_theme = "light"
list_pages = false
twitter_card = true

header_nav = [
  { url = "/", name_en = "/home/", name_fr = "/accueil/" },
  { url = "/about", name_en = "/about/", name_fr = "/concernant/" },
  { url = "/journal", name_en = "/journal/", name_fr = "/journal/" },
  { url = "/blog", name_en = "/blog/", name_fr = "/blog/" }
]

# Optional footer license text. It will only show, when using footer_content_license.
#footer_content_license = "Creative Commons Attribution 4.0 International"
#footer_content_license_link = "https://creativecommons.org/licenses/by/4.0/"
